version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: shorts_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: shorts_backend
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./storage:/app/storage
    command: ["node", "dist/index.js"]

  # Optional Redis for BullMQ queue
  # redis:
  #   image: redis:7-alpine
  #   container_name: shorts_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  frontend:
    build: ./frontend
    container_name: shorts_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:4000

volumes:
  mongo_data:
  # redis_data:
