name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'render.yaml'
      - '.github/workflows/deploy-backend-render.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -sSL -X POST "$RENDER_BACKEND_HOOK_URL"
        env:
          RENDER_BACKEND_HOOK_URL: ${{ secrets.RENDER_BACKEND_HOOK_URL }}